version: '2'
services:
  web:
    build:
      context: .
      dockerfile: docker/app.dockerfile
    command: npm start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      - "CONNECTION_STRING=mysql://movies:secret@database/movies"
  database:
    image: mariadb
    environment:
      - "MYSQL_DATABASE=movies"
      - "MYSQL_USER=movies"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
        - "33061:3306"
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata:
